# Generated by Django 3.0.7 on 2020-06-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_CAIDA_TENSION', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datoscalculoctmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
