version: "3"

services:
  api_model:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./app:/usr/src/app/app
      - ./db.sqlite3:/usr/src/app/db.sqlite3
    restart: always
